version: 2
jobs:
  test:
    docker: 
      - image: node:8.9.4
    working_directory: ~/app
    steps:
      - checkout
      - run: npm i
      - run: npm test
  deploy-staging:
    docker: 
      - image: node:8.9.4
    working_directory: ~/app
    steps:
      - checkout
      - run: ls
      - run: npm run build
      - run: echo "Production deploy"
  deploy-production:
    docker: 
      - image: node:8.9.4
    working_directory: ~/app
    steps:
      - checkout
      - run: ls
      - run: npm run build
      - run: echo "Production deploy"
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy-production:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
